name: App CI
on:
    workflow_call:

permissions:
  id-token: write   #for OIDC
  contents: read    

jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12.3'
            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m pip install -r requirements.txt
                  python3 -m pip install -r requirements-dev.txt
            - name: Run linting tests
              run: flake8 flaskr/

    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12.3'
            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m pip install -r requirements.txt
                  python3 -m pip install -r requirements-dev.txt
            - name: Run functional tests
              run: python3 -m pytest --cov=flaskr tests/ --cov-fail-under=70

    filesystem_scanning:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Run filesystem scan for vulnerabilities
              uses: aquasecurity/trivy-action@0.35.0
              with:
                  scan-type: 'fs'
                  scan-ref: '.'
                  scanners: 'vuln,secret,misconfig'
                  severity: 'HIGH,CRITICAL'
                  exit-code: '1'

    build-and-push:        
        needs: [linting, tests, filesystem_scanning]
        runs-on: ubuntu-latest
        outputs:
          tag: ${{ steps.get-tag.outputs.image_tag }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Get short SHA for image tag
              id: get-tag
              run: echo "image_tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

            - name: Build image
              run: docker build --pull -t flask-app:${{github.sha}} .

            - name: Scan image
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: flask-app:${{github.sha}}
                  ignore-unfixed: true    
                  vuln-type: os,library   
                  severity: 'HIGH,CRITICAL'
                  exit-code: '1'

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v6
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: ${{ secrets.AWS_REGION }}
                audience: sts.amazonaws.com

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
                
            - name: Push image to ECR
              env:
                REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                REPOSITORY: ops-blog/flask-app
              run: |
                docker tag flask-app:${{github.sha}} $REGISTRY/$REPOSITORY:${{ steps.get-tag.outputs.image_tag }}
                docker push $REGISTRY/$REPOSITORY:${{ steps.get-tag.outputs.image_tag }}
                
    deploy:
        needs: [build-and-push]
        uses: ./.github/workflows/infra-cd.yaml
        with:
            image_tag: ${{ needs.build-and-push.outputs.tag }}
        secrets: inherit      

             