name: CI 
on:
    workflow_dispatch:
    pull_request:
        branches: [ staging, main ]
    push:
        branches: [ staging, main, feat/* ]

permissions:
  id-token: write   #for OIDC
  contents: read    

jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12.3'
            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m pip install -r requirements.txt
                  python3 -m pip install -r requirements-dev.txt
            - name: Run linting tests
              run: flake8 flaskr/
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12.3'
            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m pip install -r requirements.txt
                  python3 -m pip install -r requirements-dev.txt
            - name: Run functional tests
              run: python3 -m pytest --cov=flaskr tests/ --cov-fail-under=70
    filesystem_scanning:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Run filesystem scan for vulnerabilities
              uses: aquasecurity/trivy-action@0.35.0
              with:
                  scan-type: 'fs'
                  scan-ref: '.'
                  scanners: 'vuln,secret,misconfig'
                  severity: 'HIGH,CRITICAL'
                  exit-code: '1'
    build-and-push:
        runs-on: ubuntu-latest
        needs: tests
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set image tag
              id: tag
              run: echo "image_tag=flask-app:${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
                
            - name: Build and push image
              env:
                REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                REPOSITORY: ops-blog/flask-app
              run: |
                docker build --pull -t $REGISTRY/$REPOSITORY:${{ steps.tag.outputs.image_tag }} .
                docker push $REGISTRY/$REPOSITORY:${{ steps.tag.outputs.image_tag }}
                
            - name: Scan image
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: ${{ steps.tag.outputs.image_tag }}
                  ignore-unfixed: true    
                  vuln-type: os,library   
                  severity: 'HIGH,CRITICAL'
                  exit-code: '1'

              